### ISSUE TITLE
Camera freeze in iOS 11

### ISSUE THREAD

**Issue by fabrizotus** [finn-no/Finjinon#21]
The problem occurs mainly when back from background

**Comment by 3lvis** [comment]
@fabrizotus Hi! I wasn't able to reproduce this issue, would you mind adding steps to reproduce or attaching a video to see how to reproduce it?

Thanks!

**Comment by 3lvis** [comment]
Closing until we get more info.

**Comment by Bemisal** [comment]
Open camera than lock the device for a minute or two and than unlock the device you will see camera is freezed .

**Comment by osanoj** [comment]
@Bemisal Is that on iOS 11 or newer version? I tried on my device and it seems to work.

**Comment by Bemisal** [comment]
i am facing this on ios 12.4.8,13 and 14 also i have upgraded to version 4.1 and i have noticed i am not  able to set maximumImageCount property anymore .

**Comment by Bemisal** [comment]
open some apps in background and than try to reproduce .  i am uploading video for reference as well. 

[iisue.MP4.zip](https://github.com/finn-no/Finjinon/files/5529937/iisue.MP4.zip)
