### ISSUE TITLE
How to Add Front Camera ?

### ISSUE THREAD

**Issue by KarthikMandava** [finn-no/Finjinon#27]
Hi, I am using this library for capturing multiple images without showing preview and it's working fine. But I need to change camera to front. How is it possible ?

**Comment by 3lvis** [comment]
Hi @KarthikMandava,

We don't have support for it at the moment and have kept the library in maintenance mode, so no further improvements are planned at the moment. You might want to give a try to this library which already has what you are looking for: https://github.com/hyperoslo/ImagePicker
