### ISSUE TITLE
New deprecation warnings

### ISSUE THREAD

**Issue by azimtri** [finn-no/Finjinon#34]
- flashMode' was deprecated in iOS 10.0: Use AVCapturePhotoSettings.flashMode instead.
- 'isFlashModeSupported' was deprecated in iOS 10.0: Use AVCapturePhotoOutput's -supportedFlashModes instead.
-AVCaptureStillImageOutput' was deprecated in iOS 10.0: Use AVCapturePhotoOutput instead.

could you resolve this issues ?

**Comment by 3lvis** [comment]
Hi @azimtri,

Thanks for the report, we'll look into it.

**Comment by robinsalehjan** [comment]
Hi @azimtri,

Closing this as it got fixed in PR (#40).
