### ISSUE TITLE
Ability to select multiple pictures from Gallery/Photos

### ISSUE THREAD

**Issue by manikantagarikipati** [finn-no/Finjinon#42]
Currently, the plugin supports only single image selection from the gallery ( After Clicking Photos button). Can we have the functionality of multiple image selection?

**Comment by 3lvis** [comment]
Hi @manikantagarikipati, we use QBImagePickerController for this but would be nice to integrate it inside our library since we don't need it for anything else.

**Comment by osanoj** [comment]
Closing this issue, we use another image picker for this so currently there is no plan to add this feature to this library.
